// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonToggleTheme: typeof import('./src/components/ButtonToggleTheme.vue')['default']
    Experiments001: typeof import('./src/components/Experiments/Experiments001.vue')['default']
    IconBxBxMoon: typeof import('~icons/bx/bx-moon')['default']
    IconBxBxSun: typeof import('~icons/bx/bx-sun')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.7.19_sass@1.45.1/node_modules/iles/dist/client/app/components/Island.vue')['default']
    Listing: typeof import('./src/components/Listing.vue')['default']
  }
}

export { }
