/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonToggleTheme: typeof import('./src/components/ButtonToggleTheme.vue')['default']
    Composables: typeof import('./src/components/Experiments/Experiments001/composables.ts')['default']
    Experiments001: typeof import('./src/components/Experiments/Experiments001/Experiments001.vue')['default']
    Experiments001Container: typeof import('./src/components/Experiments/Experiments001/Experiments001Container.vue')['default']
    Experiments001Dot: typeof import('./src/components/Experiments/Experiments001/Experiments001Dot.vue')['default']
    Experiments002: typeof import('./src/components/Experiments/Experiments002/Experiments002.vue')['default']
    Experiments002Circle: typeof import('./src/components/Experiments/Experiments002/Experiments002Circle.vue')['default']
    Experiments003: typeof import('./src/components/Experiments/Experiments003/Experiments003.vue')['default']
    Experiments003Anchor: typeof import('./src/components/Experiments/Experiments003/Experiments003Anchor.vue')['default']
    IconBxBxMoon: typeof import('~icons/bx/bx-moon')['default']
    IconBxBxSun: typeof import('~icons/bx/bx-sun')['default']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    Listing: typeof import('./src/components/Listing.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MetaInfo: typeof import('./src/components/MetaInfo.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    PreviewPlayground: typeof import('./src/components/PreviewPlayground.vue')['default']
    RenderFeed: typeof import('./node_modules/@islands/feed/dist/render-feed')['RenderFeed']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableOfContent: typeof import('./src/components/TableOfContent.vue')['default']
  }
}
